-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 07, 2025 at 12:00 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `solarenergy`
--

--
-- Dumping data for table `options`
--

INSERT INTO `options` (`id`, `option_name`, `option_value`) VALUES
(1, 'company_name_fa', 'انرژی امین کسری'),
(2, 'company_name_en', 'Amin Kasra Energy'),
(3, 'company_quote_fa', 'پیشرو در حرکت به سوی آینده‌ای روشن‌تر و پاک‌تر.'),
(4, 'company_quote_en', 'Leading the charge towards a brighter, cleaner future.'),
(5, 'contact_address_fa', 'تهران، خیابان خورشیدی، پلاک ۱۲۳'),
(6, 'contact_address_en', '123 Solar Avenue, Tehran, Iran'),
(7, 'contact_phone', '+98 21 1234 5678'),
(8, 'contact_email', 'info@aminkasraenergy.com');

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title_en`, `content_en`, `excerpt_en`, `title_fa`, `content_fa`, `excerpt_fa`, `image_url`, `created_at`) VALUES
(1, 'Breakthrough in Solar Panel Efficiency', '<p>In a landmark study published today, researchers have unveiled a new perovskite-based material that promises to revolutionize the solar industry. This material can be applied as a thin film over existing silicon panels, increasing their energy conversion efficiency by up to 30%. This breakthrough could make solar power significantly more cost-effective and accelerate the global transition to renewable energy.</p><p>The research, conducted by a joint team from the National Renewable Energy Laboratory and the University of Cambridge, focused on stabilizing the notoriously volatile perovskite crystals. By developing a novel encapsulation technique, the team was able to create a durable material that withstands heat and moisture, two of the primary factors that have previously limited the commercial viability of perovskite solar cells. This enhanced durability means the new hybrid panels will have a lifespan comparable to traditional silicon panels, making them a practical and powerful alternative.</p>', 'Scientists have developed a new material that could significantly boost the efficiency of solar panels.', 'پیشرفتی چشمگیر در بازدهی پنل‌های خورشیدی', '<p>در یک مطالعه برجسته که امروز منتشر شد، پژوهشگران از یک ماده جدید مبتنی بر پروسکایت رونمایی کرده‌اند که وعده تحول در صنعت خورشیدی را می‌دهد. این ماده می‌تواند به صورت یک لایه نازک روی پنل‌های سیلیکونی موجود اعمال شود و بازدهی تبدیل انرژی آن‌ها را تا ۳۰ درصد افزایش دهد. این پیشرفت می‌تواند انرژی خورشیدی را به طور قابل توجهی مقرون‌به‌صرفه‌تر کرده و گذار جهانی به انرژی‌های تجدیدپذیر را تسریع بخشد.</p><p>این پژوهش که توسط یک تیم مشترک از آزمایشگاه ملی انرژی‌های تجدیدپذیر و دانشگاه کمبریج انجام شده است، بر پایدارسازی بلورهای پروسکایت که به بی‌ثباتی شهرت دارند، متمرکز بود. با توسعه یک تکنیک کپسوله‌سازی نوین، این تیم موفق به ساخت ماده‌ای با دوام شد که در برابر حرارت و رطوبت، دو عامل اصلی که پیش از این مانع تجاری‌سازی سلول‌های خورشیدی پروسکایت شده بودند، مقاومت می‌کند. این دوام افزایش‌یافته به این معناست که پنل‌های هیبریدی جدید، عمری قابل مقایسه با پنل‌های سیلیکونی سنتی خواهند داشت و آن‌ها را به یک جایگزین عملی و قدرتمند تبدیل می‌کند.</p>', 'دانشمندان ماده جدیدی را توسعه داده‌اند که می‌تواند بازدهی پنل‌های خورشیدی را به طور قابل توجهی افزایش دهد.', 'https://picsum.photos/seed/news1/600/400', '2025-12-07 00:00:00'),
(2, 'Global Shift to Renewable Energy', '<p>The International Energy Agency (IEA) has released its annual report, showing a record increase in renewable energy capacity worldwide. Solar power accounted for over two-thirds of this growth. The report emphasizes that government policies and falling technology costs are the primary drivers of this rapid shift. Experts believe we are at a critical tipping point in the fight against climate change.</p><p>The report, titled "Renewables 2025," details how solar, wind, and hydropower are becoming the backbone of the world\'s electricity supply. It highlights that the cost of solar photovoltaic (PV) generation has plummeted by over 80% in the last decade, making it the cheapest source of new electricity in many parts of the world. The IEA forecasts that this trend will continue, with renewables set to overtake coal as the largest source of electricity generation globally by 2025. This transition is critical for meeting the goals of the Paris Agreement and ensuring a sustainable energy future.</p>', 'A new report highlights the accelerating trend of countries moving away from fossil fuels towards renewables.', 'تغییر جهانی به سمت انرژی‌های تجدیدپذیر', '<p>آژانس بین‌المللی انرژی (IEA) گزارش سالانه خود را منتشر کرده است که نشان‌دهنده افزایش بی‌سابقه ظرفیت انرژی‌های تجدیدپذیر در سراسر جهان است. انرژی خورشیدی بیش از دو سوم این رشد را به خود اختصاص داده است. این گزارش تأکید می‌کند که سیاست‌های دولتی و کاهش هزینه‌های فناوری، محرک‌های اصلی این تغییر سریع هستند. کارشناسان معتقدند ما در یک نقطه عطف حیاتی در مبارزه با تغییرات اقلیمی قرار داریم.</p><p>این گزارش با عنوان "تجدیدپذیرها ۲۰۲۵"، به تفصیل شرح می‌دهد که چگونه انرژی خورشیدی، بادی و برق‌آبی در حال تبدیل شدن به ستون فقرات تأمین برق جهان هستند. در این گزارش آمده است که هزینه تولید فتوولتائیک خورشیدی (PV) در دهه گذشته بیش از ۸۰ درصد کاهش یافته و آن را به ارزان‌ترین منبع برق جدید در بسیاری از نقاط جهان تبدیل کرده است. آژانس بین‌المللی انرژی پیش‌بینی می‌کند که این روند ادامه خواهد داشت و انرژی‌های تجدیدپذیر تا سال ۲۰۲۵ از زغال‌سنگ به عنوان بزرگترین منبع تولید برق در سطح جهان پیشی خواهند گرفت. این گذار برای دستیابی به اهداف توافقنامه پاریس و تضمین آینده‌ای پایدار برای انرژی، حیاتی است.</p>', 'گزارش جدیدی بر روند شتابان کشورها در حرکت از سوخت‌های فسیلی به سمت انرژی‌های تجدیدپذیر تأکید دارد.', 'https://picsum.photos/seed/news2/600/400', '2025-12-07 00:00:00'),
(3, 'Amin Kasra Energy’s New Community Project', '<p>Amin Kasra Energy has broken ground on a new 25-megawatt solar farm. Located just outside the city, this project is a significant step towards achieving local energy independence. The farm is expected to be operational by the end of next year and will provide clean, reliable power to over 5,000 homes, reducing carbon emissions by an estimated 30,000 tons annually. This initiative is part of our ongoing commitment to a sustainable future.</p><p>The project will also create approximately 150 jobs during its construction phase and a dozen permanent positions for ongoing maintenance and operation. We are partnering with local community colleges to provide training programs for these new green-collar jobs. Furthermore, the land beneath the solar panels will be used for agrivoltaics, allowing for the cultivation of shade-tolerant crops and creating a dual-use system that benefits both the energy and agricultural sectors of the region.</p>', 'We are proud to announce our latest project, a solar farm that will power over 5,000 homes.', 'پروژه اجتماعی جدید شرکت انرژی امین کسری', '<p>شرکت انرژی امین کسری عملیات احداث یک مزرعه خورشیدی جدید ۲۵ مگاواتی را آغاز کرده است. این پروژه که در حومه شهر واقع شده، گام مهمی در جهت دستیابی به استقلال انرژی محلی است. انتظار می‌رود این مزرعه تا پایان سال آینده به بهره‌برداری برسد و برق پاک و قابل اعتمادی را برای بیش از ۵۰۰۰ خانه فراهم کند و سالانه حدود ۳۰٬۰۰۰ تن از انتشار کربن بکاهد. این ابتکار بخشی از تعهد مستمر ما به آینده‌ای پایدار است.</p><p>این پروژه همچنین در مرحله ساخت حدود ۱۵۰ شغل و برای نگهداری و بهره‌برداری مداوم، ده‌ها موقعیت شغلی دائمی ایجاد خواهد کرد. ما در حال همکاری با کالج‌های محلی برای ارائه برنامه‌های آموزشی برای این مشاغل جدید "یقه سبز" هستیم. علاوه بر این، زمین زیر پنل‌های خورشیدی برای کشاورزی خورشیدی (agrivoltaics) استفاده خواهد شد که امکان کشت محصولات مقاوم به سایه را فراهم کرده و یک سیستم دو منظوره ایجاد می‌کند که به نفع هر دو بخش انرژی و کشاورزی منطقه خواهد بود.</p>', 'ما با افتخار جدیدترین پروژه خود را معرفی می‌کنیم، یک مزرعه خورشیدی که انرژی بیش از ۵۰۰۰ خانه را تأمین خواهد کرد.', 'https://picsum.photos/seed/news3/600/400', '2025-12-07 00:00:00'),
(4, 'How Do Solar Panels Work?', '<p>Solar panels are composed of photovoltaic (PV) cells, which are typically made from silicon, a semiconductor. Each cell has two layers of silicon, one positively charged (p-type) and one negatively charged (n-type). When sunlight, which is made of tiny particles called photons, strikes the surface of the PV cell, it energizes the electrons in the silicon. This energy allows the electrons to break free from their atoms and move between the two silicon layers.</p><p>This movement creates an electric field across the junction between the layers. The electric field acts like a slide, forcing the freed electrons to flow in one direction. This flow of electrons is known as a direct current (DC). Metal contacts on the top and bottom of the solar cell collect this DC electricity. From there, it is sent to a solar inverter, which is a crucial component of the system. The inverter transforms the DC electricity into alternating current (AC), the type of electricity used by standard home appliances and the power grid. This clean, silent process harnesses the most abundant energy source on our planet to generate usable power.</p>', 'A brief explanation of the photovoltaic process that powers our world.', 'پنل‌های خورشیدی چگونه کار می‌کنند؟', '<p>پنل‌های خورشیدی از سلول‌های فتوولتائیک (PV) تشکیل شده‌اند که معمولاً از سیلیکون، یک نیمه‌رسانا، ساخته می‌شوند. هر سلول دارای دو لایه سیلیکون است، یکی با بار مثبت (نوع p) و دیگری با بار منفی (نوع n). هنگامی که نور خورشید، که از ذرات ریزی به نام فوتون تشکیل شده است، به سطح سلول PV برخورد می‌کند، به الکترون‌های موجود در سیلیکون انرژی می‌دهد. این انرژی به الکترون‌ها اجازه می‌دهد تا از اتم‌های خود جدا شده و بین دو لایه سیلیکون حرکت کنند.</p><p>این حرکت یک میدان الکتریکی در سراسر محل اتصال بین لایه‌ها ایجاد می‌کند. میدان الکتریکی مانند یک سرسره عمل کرده و الکترون‌های آزاد شده را مجبور می‌کند تا در یک جهت جریان یابند. این جریان الکترون‌ها به عنوان جریان مستقیم (DC) شناخته می‌شود. اتصالات فلزی در بالا و پایین سلول خورشیدی این برق DC را جمع‌آوری می‌کنند. از آنجا، این برق به یک اینورتر خورشیدی ارسال می‌شود که جزء حیاتی سیستم است. اینورتر برق DC را به جریان متناوب (AC) تبدیل می‌کند، نوعی از برق که توسط لوازم خانگی استاندارد و شبکه برق استفاده می‌شود. این فرآیند پاک و بی‌صدا، فراوان‌ترین منبع انرژی روی سیاره ما را برای تولید برق قابل استفاده مهار می‌کند.</p>', 'توضیحی مختصر درباره فرآیند فتوولتائیک که به دنیای ما نیرو می‌بخشد.', 'https://picsum.photos/seed/post4/600/400', '2025-12-07 00:00:00'),
(5, 'The Environmental Benefits of Solar Energy', '<p>Switching to solar power offers significant environmental advantages that are crucial in the global effort to combat climate change. The most important benefit is that solar energy is a completely clean energy source. It produces no greenhouse gas emissions, such as carbon dioxide (CO2), which are the primary drivers of global warming. By reducing our collective carbon footprint, solar power helps to mitigate the long-term effects of climate change.</p><p>Furthermore, unlike traditional fossil fuels like coal and natural gas, solar energy generation does not release harmful pollutants like sulfur dioxide, nitrogen oxides, and particulate matter into the atmosphere. These pollutants are responsible for acid rain, smog, and various respiratory illnesses. Solar power also requires very little water to operate, a stark contrast to traditional power plants that consume vast amounts of water for cooling. By conserving precious water resources and keeping our air and water clean, solar energy promotes a more sustainable and healthier planet for future generations. Every panel installed is a concrete step towards a cleaner, more resilient world.</p>', 'Discover how solar power helps protect our planet.', 'مزایای زیست‌محیطی انرژی خورشیدی', '<p>روی آوردن به انرژی خورشیدی مزایای زیست‌محیطی قابل توجهی را به همراه دارد که در تلاش جهانی برای مبارزه با تغییرات اقلیمی، بسیار حیاتی است. مهم‌ترین مزیت این است که انرژی خورشیدی یک منبع انرژی کاملاً پاک است. این انرژی هیچ‌گونه گاز گلخانه‌ای، مانند دی‌اکسید کربن (CO2) که عامل اصلی گرمایش جهانی هستند، تولید نمی‌کند. انرژی خورشیدی با کاهش ردپای کربنی جمعی ما، به کاهش اثرات بلندمدت تغییرات اقلیمی کمک می‌کند.</p><p>علاوه بر این، برخلاف سوخت‌های فسیلی سنتی مانند زغال‌سنگ و گاز طبیعی، تولید انرژی خورشیدی آلاینده‌های مضری مانند دی‌اکسید گوگرد، اکسیدهای نیتروژن و ذرات معلق را در جو آزاد نمی‌کند. این آلاینده‌ها مسئول باران‌های اسیدی، مه‌دود و بیماری‌های مختلف تنفسی هستند. انرژی خورشیدی همچنین برای کار کردن به آب بسیار کمی نیاز دارد، که تضاد آشکاری با نیروگاه‌های سنتی دارد که مقادیر عظیمی از آب را برای خنک‌سازی مصرف می‌کنند. با حفاظت از منابع گران‌بهای آب و پاک نگه داشتن هوا و آب، انرژی خورشیدی سیاره‌ای پایدارتر و سالم‌تر برای نسل‌های آینده ترویج می‌دهد. هر پنلی که نصب می‌شود، گامی ملموس به سوی دنیایی پاک‌تر و مقاوم‌تر است.</p>', 'کشف کنید که چگونه انرژی خورشیدی به حفاظت از سیاره ما کمک می‌کند.', 'https://picsum.photos/seed/post5/600/400', '2025-12-07 00:00:00'),
(6, 'Economic Advantages of Going Solar', '<p>Investing in solar panels is not just good for the environment; it’s also a smart financial decision with long-term benefits. The most significant economic advantage is the potential to drastically reduce or even eliminate your electricity bills. By generating your own power, you purchase less electricity from the utility company, saving a substantial amount of money each month for the 25-30 year lifespan of the solar panel system.</p><p>Additionally, many governments and local municipalities offer attractive financial incentives to encourage the adoption of solar energy. These can include generous tax credits that reduce your federal income tax, cash rebates, and performance-based incentives that pay you for the electricity your system generates. Furthermore, installing solar panels can significantly increase the value of your property. Studies have shown that homes with solar panels sell faster and at higher prices than those without. By gaining energy independence, you are also protected from the volatility of future utility rate hikes, ensuring predictable and stable energy expenses for years to come.</p>', 'Learn how solar panels can save you money and increase your energy independence.', 'مزایای اقتصادی روی آوردن به انرژی خورشیدی', '<p>سرمایه‌گذاری در پنل‌های خورشیدی تنها برای محیط زیست مفید نیست؛ بلکه یک تصمیم مالی هوشمندانه با مزایای بلندمدت نیز محسوب می‌شود. مهم‌ترین مزیت اقتصادی، پتانسیل کاهش شدید یا حتی حذف کامل قبض‌های برق شماست. با تولید برق خود، شما برق کمتری از شرکت برق خریداری می‌کنید و هر ماه مبلغ قابل توجهی را در طول عمر ۲۵ تا ۳۰ ساله سیستم پنل خورشیدی پس‌انداز می‌کنید.</p><p>علاوه بر این، بسیاری از دولت‌ها و شهرداری‌های محلی، مشوق‌های مالی جذابی را برای تشویق به استفاده از انرژی خورشیدی ارائه می‌دهند. این مشوق‌ها می‌توانند شامل اعتبارات مالیاتی سخاوتمندانه‌ای باشند که مالیات بر درآمد فدرال شما را کاهش می‌دهند، تخفیف‌های نقدی، و مشوق‌های مبتنی بر عملکرد که به ازای برقی که سیستم شما تولید می‌کند به شما پول پرداخت می‌کنند. علاوه بر این، نصب پنل‌های خورشیدی می‌تواند به طور قابل توجهی ارزش ملک شما را افزایش دهد. مطالعات نشان داده‌اند که خانه‌های دارای پنل خورشیدی سریع‌تر و با قیمت‌های بالاتری نسبت به خانه‌های بدون آن به فروش می‌رسند. با دستیابی به استقلال انرژی، شما همچنین از نوسانات افزایش نرخ‌های آینده شرکت‌های برق در امان می‌مانید و هزینه‌های انرژی قابل پیش‌بینی و پایداری را برای سال‌های آینده تضمین می‌کنید.</p>', 'بیاموزید که چگونه پنل‌های خورشیدی می‌توانند در پول شما صرفه‌جویی کرده و استقلال انرژی شما را افزایش دهند.', 'https://picsum.photos/seed/post6/600/400', '2025-12-07 00:00:00');

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
