
import type { Translations } from '../types';

export const en: Translations = {
  header: {
    home: "Home",
    activities: "Activities",
    news: "News & Articles",
    about: "About Us",
    contact: "Contact Us",
    switchLanguage: "فارسی",
    companyName: "Solar Transition Co.",
  },
  hero: {
    title: "Powering Tomorrow, Sustainably",
    subtitle: "Transitioning from a legacy in oil and gas to a future in clean, renewable solar energy.",
    cta: "Discover Our Services",
  },
  home: {
    section1Title: "A New Dawn in Energy",
    section1Text: "Leveraging our extensive experience in the energy sector, we are now dedicated to pioneering solar solutions. We believe in a sustainable future and are committed to making clean energy accessible and affordable for everyone.",
    section2Title: "Why Choose Us?",
    section2Text: "With decades of expertise in large-scale energy projects, we bring unparalleled reliability, efficiency, and innovation to the renewable energy landscape. Our transition is not just a change in focus, but an evolution of our commitment to powering the world.",
    section3Title: "Our Core Values",
    section3Item1: "Sustainability",
    section3Item2: "Innovation",
    section3Item3: "Reliability",
  },
  activities: {
    title: "Our Activities",
    intro: "We offer a comprehensive suite of services to meet the growing demand for solar energy, from residential projects to large-scale industrial installations.",
    activity1Title: "Solar Farm Development",
    activity1Text: "End-to-end development of utility-scale solar farms, including site assessment, engineering, procurement, and construction (EPC).",
    activity2Title: "Commercial & Industrial Solutions",
    activity2Text: "Customized solar solutions for businesses to reduce operational costs, and enhance their environmental credentials.",
    activity3Title: "Residential Solar Systems",
    activity3Text: "Providing homeowners with high-efficiency solar panel systems to achieve energy independence and lower electricity bills.",
    activity4Title: "Energy Consulting & Audits",
    activity4Text: "Expert analysis and strategic advice to optimize energy consumption and integrate renewable sources effectively.",
  },
  news: {
    title: "News & Articles",
    intro: "Stay informed about our latest projects, industry trends, and insights into the world of renewable energy.",
    article1Title: "Company Completes First 100MW Solar Park",
    article1Text: "We are proud to announce the successful commissioning of our flagship solar park, a major milestone in our green energy journey.",
    article2Title: "The Future of Solar Technology",
    article2Text: "An in-depth look at the upcoming innovations in photovoltaic cells and energy storage that will shape our future.",
    article3Title: "Making the Switch: A Guide for Businesses",
    article3Text: "Discover the financial and environmental benefits for businesses transitioning to solar energy with our comprehensive guide.",
    readMore: "Read More",
  },
  about: {
    title: "About Solar Transition Co.",
    p1: "Founded on a rich history of powering nations through oil and gas, Solar Transition Co. represents the evolution of energy. We have taken our decades of experience in project management, engineering excellence, and logistical expertise and pivoted towards a brighter, cleaner future.",
    p2: "This strategic shift is driven by our commitment to sustainability and our vision for a world powered by renewable resources. Our team of seasoned professionals from the traditional energy sector is now combined with leading experts in solar technology to create a unique synergy.",
    p3: "We understand the complexities of the energy grid and the critical importance of reliability. This deep-rooted knowledge allows us to deliver robust, efficient, and innovative solar solutions that are built to last.",
    visionTitle: "Our Vision",
    visionText: "To be a leading force in the global transition to renewable energy, creating a sustainable legacy for future generations.",
    missionTitle: "Our Mission",
    missionText: "To deliver high-quality, reliable, and affordable solar energy solutions by leveraging our profound expertise in the energy sector and our passion for innovation.",
  },
  contact: {
    title: "Get in Touch",
    intro: "We'd love to hear from you. Whether you have a question about our services or want to discuss a potential project, our team is ready to answer all your inquiries.",
    formName: "Full Name",
    formEmail: "Email Address",
    formSubject: "Subject",
    formMessage: "Your Message",
    formSubmit: "Send Message",
    infoTitle: "Contact Information",
    address: "123 Energy Lane, Tehran, Iran",
    phone: "+98 21 1234 5678",
    email: "info@solartransition.com",
  },
  footer: {
    companyQuote: "From fossil fuels to the future of energy.",
    quickLinks: "Quick Links",
    contactInfo: "Contact Info",
    copyright: "© 2024 Solar Transition Co. All rights reserved.",
  },
};
